In [2]:
# Write a Pandas program to display the dataframe in Heatmap style.

import pandas as pd
import random
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns



db=pd.DataFrame({random.randint(0,100):[random.randint(0,101) for _ in range (10)],
                 random.randint(0,100):[random.randint(0,101) for _ in range (10)],
                 random.randint(0,100):[random.randint(0,101) for _ in range (10)],
                 random.randint(0,100):[random.randint(0,101) for _ in range (10)],
                 })
l=random.randint(5,15)
for x in range(l):
    a=random.randint(1,9)
    b=random.randint(0,3)
    db.iloc[a,b]=np.nan
print(db)

      35    66    68  73
0   48.0  28.0  52.0  31
1   79.0  62.0   NaN  93
2   20.0   7.0  52.0  77
3    0.0  42.0   NaN  85
4    NaN  42.0  52.0  33
5    NaN  70.0  64.0  46
6   16.0  86.0   NaN  13
7   75.0  34.0   NaN  63
8  100.0   NaN  40.0  37
9   44.0  44.0  40.0  98

In [3]:
db.style.background_gradient() #usare background_gradient