In [2]:
# Write a Pandas program to extract specific records from the world alcohol consumption dataset, 
# starting from the 2nd row, and selecting every 5th row thereafter.

import pandas as pd
db=pd.read_csv("World_Alcohol_Dataset - MAIN.csv")
print(db.iloc[1::5])

                      country beer_servings spirit_servings wine_servings  \
1                     Albania            89             132            54
6                     Armenia            21             179            11
11                    Bahrain            42              63             7
16                     Belize           263             114             8
21                   Botswana           173              35            35
26                    Burundi            88               0             0
31   Central African Republic            17               2             1
36                    Comoros             1               3             1
41                       Cuba            93             137             5
46         Dominican Republic           193             147             9
51          Equatorial Guinea            92               0           233
56                    Finland           263             133            97
61                    Germany           346             117           175
66                     Guinea             9               0             2
71                    Hungary           234             215           185
76                       Iraq             9               3             0
81                      Japan            77             202            16
86                     Kuwait             0               0             0
91                    Lesotho            82              29             0
96                  Macedonia             ?              27            86
101                      Mali             5               1             1
106                   Moldova           109             226            18
111                   Namibia           376               3             1
116                     Niger             3               2             1
121                  Pakistan             0               0             0
126               Philippines            71             186             1
131                    Russia           247             326            73
136                    Serbia           283             131           127
141                  Slovenia           270              51           276
146                     Spain           284             157           112
151                    Sweden           152              60           186
156                  Thailand            99             258             1
161                   Tunisia            51               3            20
166      United Arab Emirates            16             135             5
171                   Vanuatu            21              18            11
176                  Zimbabwe            64              18             4

     life_expentancy                region  gdp_per_capita
1               77.8        EASTERN EUROPE            4500
6               74.8   C.W. OF IND. STATES            3500
11              76.9             NEAR EAST           16900
16              71.0   LATIN AMER. & CARIB            4900
21              65.7    SUB-SAHARAN AFRICA            9000
26              59.6    SUB-SAHARAN AFRICA             600
31              52.5    SUB-SAHARAN AFRICA            1100
36              63.5    SUB-SAHARAN AFRICA             700
41              79.1   LATIN AMER. & CARIB            2900
46              73.9   LATIN AMER. & CARIB            6000
51              58.2    SUB-SAHARAN AFRICA            2700
56              81.1        WESTERN EUROPE           27400
61              81.0        WESTERN EUROPE           27600
66              59.0    SUB-SAHARAN AFRICA            2100
71              75.8        EASTERN EUROPE           13900
76              68.9             NEAR EAST            1500
81              83.7  ASIA (EX. NEAR EAST)           28200
86              74.7             NEAR EAST           19000
91              53.7    SUB-SAHARAN AFRICA            3000
96              75.7        EASTERN EUROPE            6700
101             58.2    SUB-SAHARAN AFRICA             900
106             72.1   C.W. OF IND. STATES            1800
111             65.8    SUB-SAHARAN AFRICA            7200
116             61.8    SUB-SAHARAN AFRICA             800
121             66.4  ASIA (EX. NEAR EAST)            2100
126             68.5  ASIA (EX. NEAR EAST)            4600
131             75.0   C.W. OF IND. STATES            8900
136             75.6        EASTERN EUROPE            2200
141             88.0        EASTERN EUROPE           19000
146             82.8        WESTERN EUROPE           22000
151             82.4        WESTERN EUROPE           26800
156             74.9  ASIA (EX. NEAR EAST)            7400
161             75.3       NORTHERN AFRICA            6900
166             77.1             NEAR EAST           23200
171             72.0               OCEANIA            2900
176             67.0    SUB-SAHARAN AFRICA             950